# Generated by Django 5.0.2 on 2024-03-02 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pgs_data',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pgs_data',
            name='city',
            field=models.CharField(default=None, max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pgs_data',
            name='location',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
